// Package web embeds the admin UI's built static SPA assets
// (pkg/adminui/web/dist/, produced by `make ui-build` from the Svelte
// source under pkg/adminui/web/frontend/) into the server binary.
// Node and npm are build-time-only dependencies: the compiled Go binary
// carries only the static assets below.
//
// The "all:" prefix on the embed directive includes files whose name
// begins with "." or "_" (Go's default embed pattern excludes them). The
// built Vite output here does not currently produce such files, but
// "all:" is the correct default for a directory generated by an external
// build step this package does not control.
//
// # Stability
//
// Assets is the package's only exported identifier.
//
// MAY change without a major version: dist/'s contents, as the built
// SPA changes from one release to the next.
//
// MAY NOT change without a major version: Assets' signature (func() fs.FS)
// and the guarantee that it returns dist/'s contents rooted at
// index.html rather than the raw embedded tree; the embed.FS backing it
// stays a package-private var, so no caller can reassign or replace the
// asset source.
package web

import (
	"embed"
	"io/fs"
)

//go:embed all:dist
var distFS embed.FS

// assets is distFS rooted at dist/, so its paths start at index.html
// rather than at dist/index.html. Computed once at package init so every
// Assets call returns the same fs.FS. fs.Sub can only fail here if the
// embedded tree does not contain a "dist" directory, which cannot
// happen: the "//go:embed all:dist" directive above requires that
// directory to exist at compile time. A panic on that impossible case
// is a build defect, not a runtime condition to handle gracefully.
var assets = mustSubFS(distFS, "dist")

func mustSubFS(f fs.FS, dir string) fs.FS {
	sub, err := fs.Sub(f, dir)
	if err != nil {
		panic("web: distFS is missing its \"" + dir + "\" root: " + err.Error())
	}
	return sub
}

// Assets returns the admin UI's built static SPA tree: an index.html at
// its root plus the built asset files beside it. The returned fs.FS is
// read-only and shared across calls.
func Assets() fs.FS {
	return assets
}
