// Package web embeds the admin UI's built static SPA assets
// (pkg/adminui/web/dist/, produced by `make ui-build` from the Svelte
// source under pkg/adminui/web/frontend/) into the server binary.
// Node and npm are build-time-only dependencies: the compiled Go binary
// carries only the static assets below.
//
// The "all:" prefix on the embed directive includes files whose name
// begins with "." or "_" (Go's default embed pattern excludes them). The
// built Vite output here does not currently produce such files, but
// "all:" is the correct default for a directory generated by an external
// build step this package does not control.
//
// # Stability
//
// Assets is the package's only exported identifier.
//
// MAY change without a major version: dist/'s contents, as the built
// SPA changes from one release to the next.
//
// MAY NOT change without a major version: Assets' signature (func() fs.FS)
// and the guarantee that it returns dist/'s contents rooted at
// index.html rather than the raw embedded tree; the embed.FS backing it
// stays a package-private var, so no caller can reassign or replace the
// asset source; and the guarantee that the returned fs.FS is safe for
// concurrent use, since internal/server's http.Handler serves it to
// concurrent requests.
package web

import (
	"embed"
	"io/fs"
)

//go:embed all:dist
var distFS embed.FS

// assets is distFS rooted at dist/, so its paths start at index.html
// rather than at dist/index.html. Computed once at package init so every
// Assets call returns the same fs.FS. fs.Sub's only failure mode is an
// invalid second argument per fs.ValidPath (empty, absolute, or
// containing a "." or ".." element); embed.FS does not implement
// fs.SubFS, so fs.Sub never checks whether "dist" actually exists in the
// tree, and a missing directory would surface only later, on read, not
// here. "dist" is a fixed literal that trivially satisfies ValidPath, so
// this call cannot fail. The panic below documents that invariant; it is
// not a runtime condition to handle gracefully.
var assets = mustSubFS(distFS, "dist")

func mustSubFS(f fs.FS, dir string) fs.FS {
	sub, err := fs.Sub(f, dir)
	if err != nil {
		panic("web: distFS is missing its \"" + dir + "\" root: " + err.Error())
	}
	return sub
}

// Assets returns the admin UI's built static SPA tree: an index.html at
// its root plus the built asset files beside it. The returned fs.FS is
// read-only, shared across calls, and safe for concurrent use: assets is
// computed once at init from an embed.FS, which embed's own doc comment
// guarantees is safe to use from multiple goroutines simultaneously, and
// fs.Sub's wrapper around it adds no mutable state of its own.
func Assets() fs.FS {
	return assets
}
