// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cimgraph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeederModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeederMrid    string                 `protobuf:"bytes,1,opt,name=feeder_mrid,json=feederMrid,proto3" json:"feeder_mrid,omitempty"`       // mRID of the feeder container
	DatabaseType  string                 `protobuf:"bytes,2,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"` // "gridappsd", "blazegraph", "neo4j", etc.
	Distributed   bool                   `protobuf:"varint,3,opt,name=distributed,proto3" json:"distributed,omitempty"`                      // use distributed model (default false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeederModelRequest) Reset() {
	*x = GetFeederModelRequest{}
	mi := &file_cimgraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeederModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeederModelRequest) ProtoMessage() {}

func (x *GetFeederModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeederModelRequest.ProtoReflect.Descriptor instead.
func (*GetFeederModelRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeederModelRequest) GetFeederMrid() string {
	if x != nil {
		return x.FeederMrid
	}
	return ""
}

func (x *GetFeederModelRequest) GetDatabaseType() string {
	if x != nil {
		return x.DatabaseType
	}
	return ""
}

func (x *GetFeederModelRequest) GetDistributed() bool {
	if x != nil {
		return x.Distributed
	}
	return false
}

type GetPECRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeederMrid    string                 `protobuf:"bytes,1,opt,name=feeder_mrid,json=feederMrid,proto3" json:"feeder_mrid,omitempty"` // feeder to query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPECRequest) Reset() {
	*x = GetPECRequest{}
	mi := &file_cimgraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPECRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPECRequest) ProtoMessage() {}

func (x *GetPECRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPECRequest.ProtoReflect.Descriptor instead.
func (*GetPECRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{1}
}

func (x *GetPECRequest) GetFeederMrid() string {
	if x != nil {
		return x.FeederMrid
	}
	return ""
}

type GetEquipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mrid          string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"` // equipment mRID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipmentRequest) Reset() {
	*x = GetEquipmentRequest{}
	mi := &file_cimgraph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentRequest) ProtoMessage() {}

func (x *GetEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentRequest.ProtoReflect.Descriptor instead.
func (*GetEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{2}
}

func (x *GetEquipmentRequest) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

type ListFeedersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseType  string                 `protobuf:"bytes,1,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"` // optional: override database type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedersRequest) Reset() {
	*x = ListFeedersRequest{}
	mi := &file_cimgraph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedersRequest) ProtoMessage() {}

func (x *ListFeedersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedersRequest.ProtoReflect.Descriptor instead.
func (*ListFeedersRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{3}
}

func (x *ListFeedersRequest) GetDatabaseType() string {
	if x != nil {
		return x.DatabaseType
	}
	return ""
}

type SPARQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // SPARQL query string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPARQLRequest) Reset() {
	*x = SPARQLRequest{}
	mi := &file_cimgraph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPARQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPARQLRequest) ProtoMessage() {}

func (x *SPARQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPARQLRequest.ProtoReflect.Descriptor instead.
func (*SPARQLRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{4}
}

func (x *SPARQLRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_cimgraph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{5}
}

type FeederModelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FeederMrid     string                 `protobuf:"bytes,1,opt,name=feeder_mrid,json=feederMrid,proto3" json:"feeder_mrid,omitempty"`
	FeederName     string                 `protobuf:"bytes,2,opt,name=feeder_name,json=feederName,proto3" json:"feeder_name,omitempty"`
	EquipmentCount int32                  `protobuf:"varint,3,opt,name=equipment_count,json=equipmentCount,proto3" json:"equipment_count,omitempty"`
	EquipmentTypes []string               `protobuf:"bytes,4,rep,name=equipment_types,json=equipmentTypes,proto3" json:"equipment_types,omitempty"` // CIM class names found
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeederModelResponse) Reset() {
	*x = FeederModelResponse{}
	mi := &file_cimgraph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeederModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederModelResponse) ProtoMessage() {}

func (x *FeederModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederModelResponse.ProtoReflect.Descriptor instead.
func (*FeederModelResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{6}
}

func (x *FeederModelResponse) GetFeederMrid() string {
	if x != nil {
		return x.FeederMrid
	}
	return ""
}

func (x *FeederModelResponse) GetFeederName() string {
	if x != nil {
		return x.FeederName
	}
	return ""
}

func (x *FeederModelResponse) GetEquipmentCount() int32 {
	if x != nil {
		return x.EquipmentCount
	}
	return 0
}

func (x *FeederModelResponse) GetEquipmentTypes() []string {
	if x != nil {
		return x.EquipmentTypes
	}
	return nil
}

type Feeder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mrid          string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`         // geographical region name
	Subregion     string                 `protobuf:"bytes,4,opt,name=subregion,proto3" json:"subregion,omitempty"`   // sub-geographical region name
	Substation    string                 `protobuf:"bytes,5,opt,name=substation,proto3" json:"substation,omitempty"` // substation name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feeder) Reset() {
	*x = Feeder{}
	mi := &file_cimgraph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feeder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feeder) ProtoMessage() {}

func (x *Feeder) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feeder.ProtoReflect.Descriptor instead.
func (*Feeder) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{7}
}

func (x *Feeder) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *Feeder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feeder) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Feeder) GetSubregion() string {
	if x != nil {
		return x.Subregion
	}
	return ""
}

func (x *Feeder) GetSubstation() string {
	if x != nil {
		return x.Substation
	}
	return ""
}

type ListFeedersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeders       []*Feeder              `protobuf:"bytes,1,rep,name=feeders,proto3" json:"feeders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedersResponse) Reset() {
	*x = ListFeedersResponse{}
	mi := &file_cimgraph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedersResponse) ProtoMessage() {}

func (x *ListFeedersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedersResponse.ProtoReflect.Descriptor instead.
func (*ListFeedersResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{8}
}

func (x *ListFeedersResponse) GetFeeders() []*Feeder {
	if x != nil {
		return x.Feeders
	}
	return nil
}

type PowerElectronicsConnection struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Mrid          string                  `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RatedS        float64                 `protobuf:"fixed64,3,opt,name=rated_s,json=ratedS,proto3" json:"rated_s,omitempty"`            // rated apparent power (VA)
	RatedU        float64                 `protobuf:"fixed64,4,opt,name=rated_u,json=ratedU,proto3" json:"rated_u,omitempty"`            // rated voltage (V)
	MaxIFault     float64                 `protobuf:"fixed64,5,opt,name=max_i_fault,json=maxIFault,proto3" json:"max_i_fault,omitempty"` // max fault current (A)
	P             float64                 `protobuf:"fixed64,6,opt,name=p,proto3" json:"p,omitempty"`                                    // active power (W)
	Q             float64                 `protobuf:"fixed64,7,opt,name=q,proto3" json:"q,omitempty"`                                    // reactive power (VAr)
	PhaseMrids    []string                `protobuf:"bytes,8,rep,name=phase_mrids,json=phaseMrids,proto3" json:"phase_mrids,omitempty"`  // per-phase connection mRIDs
	Units         []*PowerElectronicsUnit `protobuf:"bytes,9,rep,name=units,proto3" json:"units,omitempty"`                              // child units (PV, battery, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerElectronicsConnection) Reset() {
	*x = PowerElectronicsConnection{}
	mi := &file_cimgraph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerElectronicsConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerElectronicsConnection) ProtoMessage() {}

func (x *PowerElectronicsConnection) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerElectronicsConnection.ProtoReflect.Descriptor instead.
func (*PowerElectronicsConnection) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{9}
}

func (x *PowerElectronicsConnection) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *PowerElectronicsConnection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PowerElectronicsConnection) GetRatedS() float64 {
	if x != nil {
		return x.RatedS
	}
	return 0
}

func (x *PowerElectronicsConnection) GetRatedU() float64 {
	if x != nil {
		return x.RatedU
	}
	return 0
}

func (x *PowerElectronicsConnection) GetMaxIFault() float64 {
	if x != nil {
		return x.MaxIFault
	}
	return 0
}

func (x *PowerElectronicsConnection) GetP() float64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *PowerElectronicsConnection) GetQ() float64 {
	if x != nil {
		return x.Q
	}
	return 0
}

func (x *PowerElectronicsConnection) GetPhaseMrids() []string {
	if x != nil {
		return x.PhaseMrids
	}
	return nil
}

func (x *PowerElectronicsConnection) GetUnits() []*PowerElectronicsUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

type PowerElectronicsUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mrid          string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitType      string                 `protobuf:"bytes,3,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"` // "PhotovoltaicUnit", "BatteryUnit", etc.
	MaxP          float64                `protobuf:"fixed64,4,opt,name=max_p,json=maxP,proto3" json:"max_p,omitempty"`           // max active power (W)
	MinP          float64                `protobuf:"fixed64,5,opt,name=min_p,json=minP,proto3" json:"min_p,omitempty"`           // min active power (W)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerElectronicsUnit) Reset() {
	*x = PowerElectronicsUnit{}
	mi := &file_cimgraph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerElectronicsUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerElectronicsUnit) ProtoMessage() {}

func (x *PowerElectronicsUnit) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerElectronicsUnit.ProtoReflect.Descriptor instead.
func (*PowerElectronicsUnit) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{10}
}

func (x *PowerElectronicsUnit) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *PowerElectronicsUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PowerElectronicsUnit) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *PowerElectronicsUnit) GetMaxP() float64 {
	if x != nil {
		return x.MaxP
	}
	return 0
}

func (x *PowerElectronicsUnit) GetMinP() float64 {
	if x != nil {
		return x.MinP
	}
	return 0
}

type PECListResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Connections   []*PowerElectronicsConnection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PECListResponse) Reset() {
	*x = PECListResponse{}
	mi := &file_cimgraph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PECListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PECListResponse) ProtoMessage() {}

func (x *PECListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PECListResponse.ProtoReflect.Descriptor instead.
func (*PECListResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{11}
}

func (x *PECListResponse) GetConnections() []*PowerElectronicsConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type EquipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mrid          string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CimClass      string                 `protobuf:"bytes,3,opt,name=cim_class,json=cimClass,proto3" json:"cim_class,omitempty"`                                                               // CIM class name
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // all attributes as key-value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentResponse) Reset() {
	*x = EquipmentResponse{}
	mi := &file_cimgraph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentResponse) ProtoMessage() {}

func (x *EquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentResponse.ProtoReflect.Descriptor instead.
func (*EquipmentResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{12}
}

func (x *EquipmentResponse) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *EquipmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentResponse) GetCimClass() string {
	if x != nil {
		return x.CimClass
	}
	return ""
}

func (x *EquipmentResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SPARQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // raw JSON result from SPARQL query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPARQLResponse) Reset() {
	*x = SPARQLResponse{}
	mi := &file_cimgraph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPARQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPARQLResponse) ProtoMessage() {}

func (x *SPARQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPARQLResponse.ProtoReflect.Descriptor instead.
func (*SPARQLResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{13}
}

func (x *SPARQLResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	DatabaseType  string                 `protobuf:"bytes,2,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"`
	CimProfile    string                 `protobuf:"bytes,3,opt,name=cim_profile,json=cimProfile,proto3" json:"cim_profile,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_cimgraph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cimgraph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_cimgraph_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetDatabaseType() string {
	if x != nil {
		return x.DatabaseType
	}
	return ""
}

func (x *HealthCheckResponse) GetCimProfile() string {
	if x != nil {
		return x.CimProfile
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_cimgraph_proto protoreflect.FileDescriptor

const file_cimgraph_proto_rawDesc = "" +
	"\n" +
	"\x0ecimgraph.proto\x12\bcimgraph\"\x7f\n" +
	"\x15GetFeederModelRequest\x12\x1f\n" +
	"\vfeeder_mrid\x18\x01 \x01(\tR\n" +
	"feederMrid\x12#\n" +
	"\rdatabase_type\x18\x02 \x01(\tR\fdatabaseType\x12 \n" +
	"\vdistributed\x18\x03 \x01(\bR\vdistributed\"0\n" +
	"\rGetPECRequest\x12\x1f\n" +
	"\vfeeder_mrid\x18\x01 \x01(\tR\n" +
	"feederMrid\")\n" +
	"\x13GetEquipmentRequest\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\"9\n" +
	"\x12ListFeedersRequest\x12#\n" +
	"\rdatabase_type\x18\x01 \x01(\tR\fdatabaseType\"%\n" +
	"\rSPARQLRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x14\n" +
	"\x12HealthCheckRequest\"\xa9\x01\n" +
	"\x13FeederModelResponse\x12\x1f\n" +
	"\vfeeder_mrid\x18\x01 \x01(\tR\n" +
	"feederMrid\x12\x1f\n" +
	"\vfeeder_name\x18\x02 \x01(\tR\n" +
	"feederName\x12'\n" +
	"\x0fequipment_count\x18\x03 \x01(\x05R\x0eequipmentCount\x12'\n" +
	"\x0fequipment_types\x18\x04 \x03(\tR\x0eequipmentTypes\"\x86\x01\n" +
	"\x06Feeder\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1c\n" +
	"\tsubregion\x18\x04 \x01(\tR\tsubregion\x12\x1e\n" +
	"\n" +
	"substation\x18\x05 \x01(\tR\n" +
	"substation\"A\n" +
	"\x13ListFeedersResponse\x12*\n" +
	"\afeeders\x18\x01 \x03(\v2\x10.cimgraph.FeederR\afeeders\"\x89\x02\n" +
	"\x1aPowerElectronicsConnection\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\arated_s\x18\x03 \x01(\x01R\x06ratedS\x12\x17\n" +
	"\arated_u\x18\x04 \x01(\x01R\x06ratedU\x12\x1e\n" +
	"\vmax_i_fault\x18\x05 \x01(\x01R\tmaxIFault\x12\f\n" +
	"\x01p\x18\x06 \x01(\x01R\x01p\x12\f\n" +
	"\x01q\x18\a \x01(\x01R\x01q\x12\x1f\n" +
	"\vphase_mrids\x18\b \x03(\tR\n" +
	"phaseMrids\x124\n" +
	"\x05units\x18\t \x03(\v2\x1e.cimgraph.PowerElectronicsUnitR\x05units\"\x85\x01\n" +
	"\x14PowerElectronicsUnit\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tunit_type\x18\x03 \x01(\tR\bunitType\x12\x13\n" +
	"\x05max_p\x18\x04 \x01(\x01R\x04maxP\x12\x13\n" +
	"\x05min_p\x18\x05 \x01(\x01R\x04minP\"Y\n" +
	"\x0fPECListResponse\x12F\n" +
	"\vconnections\x18\x01 \x03(\v2$.cimgraph.PowerElectronicsConnectionR\vconnections\"\xe4\x01\n" +
	"\x11EquipmentResponse\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcim_class\x18\x03 \x01(\tR\bcimClass\x12K\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2+.cimgraph.EquipmentResponse.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x0eSPARQLResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"\x8f\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12#\n" +
	"\rdatabase_type\x18\x02 \x01(\tR\fdatabaseType\x12\x1f\n" +
	"\vcim_profile\x18\x03 \x01(\tR\n" +
	"cimProfile\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion2\xe1\x03\n" +
	"\x0fCIMGraphService\x12P\n" +
	"\x0eGetFeederModel\x12\x1f.cimgraph.GetFeederModelRequest\x1a\x1d.cimgraph.FeederModelResponse\x12T\n" +
	"\x1eGetPowerElectronicsConnections\x12\x17.cimgraph.GetPECRequest\x1a\x19.cimgraph.PECListResponse\x12J\n" +
	"\fGetEquipment\x12\x1d.cimgraph.GetEquipmentRequest\x1a\x1b.cimgraph.EquipmentResponse\x12B\n" +
	"\rExecuteSPARQL\x12\x17.cimgraph.SPARQLRequest\x1a\x18.cimgraph.SPARQLResponse\x12J\n" +
	"\vListFeeders\x12\x1c.cimgraph.ListFeedersRequest\x1a\x1d.cimgraph.ListFeedersResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.cimgraph.HealthCheckRequest\x1a\x1d.cimgraph.HealthCheckResponseB5Z3github.com/PNNL-CIM-Tools/CIM-Graph/grpc_wrapper/pbb\x06proto3"

var (
	file_cimgraph_proto_rawDescOnce sync.Once
	file_cimgraph_proto_rawDescData []byte
)

func file_cimgraph_proto_rawDescGZIP() []byte {
	file_cimgraph_proto_rawDescOnce.Do(func() {
		file_cimgraph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cimgraph_proto_rawDesc), len(file_cimgraph_proto_rawDesc)))
	})
	return file_cimgraph_proto_rawDescData
}

var file_cimgraph_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cimgraph_proto_goTypes = []any{
	(*GetFeederModelRequest)(nil),      // 0: cimgraph.GetFeederModelRequest
	(*GetPECRequest)(nil),              // 1: cimgraph.GetPECRequest
	(*GetEquipmentRequest)(nil),        // 2: cimgraph.GetEquipmentRequest
	(*ListFeedersRequest)(nil),         // 3: cimgraph.ListFeedersRequest
	(*SPARQLRequest)(nil),              // 4: cimgraph.SPARQLRequest
	(*HealthCheckRequest)(nil),         // 5: cimgraph.HealthCheckRequest
	(*FeederModelResponse)(nil),        // 6: cimgraph.FeederModelResponse
	(*Feeder)(nil),                     // 7: cimgraph.Feeder
	(*ListFeedersResponse)(nil),        // 8: cimgraph.ListFeedersResponse
	(*PowerElectronicsConnection)(nil), // 9: cimgraph.PowerElectronicsConnection
	(*PowerElectronicsUnit)(nil),       // 10: cimgraph.PowerElectronicsUnit
	(*PECListResponse)(nil),            // 11: cimgraph.PECListResponse
	(*EquipmentResponse)(nil),          // 12: cimgraph.EquipmentResponse
	(*SPARQLResponse)(nil),             // 13: cimgraph.SPARQLResponse
	(*HealthCheckResponse)(nil),        // 14: cimgraph.HealthCheckResponse
	nil,                                // 15: cimgraph.EquipmentResponse.AttributesEntry
}
var file_cimgraph_proto_depIdxs = []int32{
	7,  // 0: cimgraph.ListFeedersResponse.feeders:type_name -> cimgraph.Feeder
	10, // 1: cimgraph.PowerElectronicsConnection.units:type_name -> cimgraph.PowerElectronicsUnit
	9,  // 2: cimgraph.PECListResponse.connections:type_name -> cimgraph.PowerElectronicsConnection
	15, // 3: cimgraph.EquipmentResponse.attributes:type_name -> cimgraph.EquipmentResponse.AttributesEntry
	0,  // 4: cimgraph.CIMGraphService.GetFeederModel:input_type -> cimgraph.GetFeederModelRequest
	1,  // 5: cimgraph.CIMGraphService.GetPowerElectronicsConnections:input_type -> cimgraph.GetPECRequest
	2,  // 6: cimgraph.CIMGraphService.GetEquipment:input_type -> cimgraph.GetEquipmentRequest
	4,  // 7: cimgraph.CIMGraphService.ExecuteSPARQL:input_type -> cimgraph.SPARQLRequest
	3,  // 8: cimgraph.CIMGraphService.ListFeeders:input_type -> cimgraph.ListFeedersRequest
	5,  // 9: cimgraph.CIMGraphService.HealthCheck:input_type -> cimgraph.HealthCheckRequest
	6,  // 10: cimgraph.CIMGraphService.GetFeederModel:output_type -> cimgraph.FeederModelResponse
	11, // 11: cimgraph.CIMGraphService.GetPowerElectronicsConnections:output_type -> cimgraph.PECListResponse
	12, // 12: cimgraph.CIMGraphService.GetEquipment:output_type -> cimgraph.EquipmentResponse
	13, // 13: cimgraph.CIMGraphService.ExecuteSPARQL:output_type -> cimgraph.SPARQLResponse
	8,  // 14: cimgraph.CIMGraphService.ListFeeders:output_type -> cimgraph.ListFeedersResponse
	14, // 15: cimgraph.CIMGraphService.HealthCheck:output_type -> cimgraph.HealthCheckResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cimgraph_proto_init() }
func file_cimgraph_proto_init() {
	if File_cimgraph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cimgraph_proto_rawDesc), len(file_cimgraph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cimgraph_proto_goTypes,
		DependencyIndexes: file_cimgraph_proto_depIdxs,
		MessageInfos:      file_cimgraph_proto_msgTypes,
	}.Build()
	File_cimgraph_proto = out.File
	file_cimgraph_proto_goTypes = nil
	file_cimgraph_proto_depIdxs = nil
}
