// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cimgraph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CIMGraphService_GetFeederModel_FullMethodName                 = "/cimgraph.CIMGraphService/GetFeederModel"
	CIMGraphService_GetPowerElectronicsConnections_FullMethodName = "/cimgraph.CIMGraphService/GetPowerElectronicsConnections"
	CIMGraphService_GetEquipment_FullMethodName                   = "/cimgraph.CIMGraphService/GetEquipment"
	CIMGraphService_ExecuteSPARQL_FullMethodName                  = "/cimgraph.CIMGraphService/ExecuteSPARQL"
	CIMGraphService_HealthCheck_FullMethodName                    = "/cimgraph.CIMGraphService/HealthCheck"
)

// CIMGraphServiceClient is the client API for CIMGraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CIMGraphService provides gRPC access to CIM-Graph's Python library
// for discovering and querying CIM power system models.
type CIMGraphServiceClient interface {
	// GetFeederModel loads a feeder model and returns its metadata.
	GetFeederModel(ctx context.Context, in *GetFeederModelRequest, opts ...grpc.CallOption) (*FeederModelResponse, error)
	// GetPowerElectronicsConnections returns all DER equipment in a feeder.
	GetPowerElectronicsConnections(ctx context.Context, in *GetPECRequest, opts ...grpc.CallOption) (*PECListResponse, error)
	// GetEquipment returns details for a specific equipment by mRID.
	GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*EquipmentResponse, error)
	// ExecuteSPARQL runs a raw SPARQL query against the connected database.
	ExecuteSPARQL(ctx context.Context, in *SPARQLRequest, opts ...grpc.CallOption) (*SPARQLResponse, error)
	// HealthCheck verifies the service and database connection are alive.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type cIMGraphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCIMGraphServiceClient(cc grpc.ClientConnInterface) CIMGraphServiceClient {
	return &cIMGraphServiceClient{cc}
}

func (c *cIMGraphServiceClient) GetFeederModel(ctx context.Context, in *GetFeederModelRequest, opts ...grpc.CallOption) (*FeederModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeederModelResponse)
	err := c.cc.Invoke(ctx, CIMGraphService_GetFeederModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIMGraphServiceClient) GetPowerElectronicsConnections(ctx context.Context, in *GetPECRequest, opts ...grpc.CallOption) (*PECListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PECListResponse)
	err := c.cc.Invoke(ctx, CIMGraphService_GetPowerElectronicsConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIMGraphServiceClient) GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*EquipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EquipmentResponse)
	err := c.cc.Invoke(ctx, CIMGraphService_GetEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIMGraphServiceClient) ExecuteSPARQL(ctx context.Context, in *SPARQLRequest, opts ...grpc.CallOption) (*SPARQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SPARQLResponse)
	err := c.cc.Invoke(ctx, CIMGraphService_ExecuteSPARQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIMGraphServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CIMGraphService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CIMGraphServiceServer is the server API for CIMGraphService service.
// All implementations must embed UnimplementedCIMGraphServiceServer
// for forward compatibility.
//
// CIMGraphService provides gRPC access to CIM-Graph's Python library
// for discovering and querying CIM power system models.
type CIMGraphServiceServer interface {
	// GetFeederModel loads a feeder model and returns its metadata.
	GetFeederModel(context.Context, *GetFeederModelRequest) (*FeederModelResponse, error)
	// GetPowerElectronicsConnections returns all DER equipment in a feeder.
	GetPowerElectronicsConnections(context.Context, *GetPECRequest) (*PECListResponse, error)
	// GetEquipment returns details for a specific equipment by mRID.
	GetEquipment(context.Context, *GetEquipmentRequest) (*EquipmentResponse, error)
	// ExecuteSPARQL runs a raw SPARQL query against the connected database.
	ExecuteSPARQL(context.Context, *SPARQLRequest) (*SPARQLResponse, error)
	// HealthCheck verifies the service and database connection are alive.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedCIMGraphServiceServer()
}

// UnimplementedCIMGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCIMGraphServiceServer struct{}

func (UnimplementedCIMGraphServiceServer) GetFeederModel(context.Context, *GetFeederModelRequest) (*FeederModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeederModel not implemented")
}
func (UnimplementedCIMGraphServiceServer) GetPowerElectronicsConnections(context.Context, *GetPECRequest) (*PECListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPowerElectronicsConnections not implemented")
}
func (UnimplementedCIMGraphServiceServer) GetEquipment(context.Context, *GetEquipmentRequest) (*EquipmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEquipment not implemented")
}
func (UnimplementedCIMGraphServiceServer) ExecuteSPARQL(context.Context, *SPARQLRequest) (*SPARQLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSPARQL not implemented")
}
func (UnimplementedCIMGraphServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCIMGraphServiceServer) mustEmbedUnimplementedCIMGraphServiceServer() {}
func (UnimplementedCIMGraphServiceServer) testEmbeddedByValue()                         {}

// UnsafeCIMGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CIMGraphServiceServer will
// result in compilation errors.
type UnsafeCIMGraphServiceServer interface {
	mustEmbedUnimplementedCIMGraphServiceServer()
}

func RegisterCIMGraphServiceServer(s grpc.ServiceRegistrar, srv CIMGraphServiceServer) {
	// If the following call panics, it indicates UnimplementedCIMGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CIMGraphService_ServiceDesc, srv)
}

func _CIMGraphService_GetFeederModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeederModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIMGraphServiceServer).GetFeederModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CIMGraphService_GetFeederModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIMGraphServiceServer).GetFeederModel(ctx, req.(*GetFeederModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIMGraphService_GetPowerElectronicsConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPECRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIMGraphServiceServer).GetPowerElectronicsConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CIMGraphService_GetPowerElectronicsConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIMGraphServiceServer).GetPowerElectronicsConnections(ctx, req.(*GetPECRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIMGraphService_GetEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIMGraphServiceServer).GetEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CIMGraphService_GetEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIMGraphServiceServer).GetEquipment(ctx, req.(*GetEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIMGraphService_ExecuteSPARQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SPARQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIMGraphServiceServer).ExecuteSPARQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CIMGraphService_ExecuteSPARQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIMGraphServiceServer).ExecuteSPARQL(ctx, req.(*SPARQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CIMGraphService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIMGraphServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CIMGraphService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIMGraphServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CIMGraphService_ServiceDesc is the grpc.ServiceDesc for CIMGraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CIMGraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cimgraph.CIMGraphService",
	HandlerType: (*CIMGraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeederModel",
			Handler:    _CIMGraphService_GetFeederModel_Handler,
		},
		{
			MethodName: "GetPowerElectronicsConnections",
			Handler:    _CIMGraphService_GetPowerElectronicsConnections_Handler,
		},
		{
			MethodName: "GetEquipment",
			Handler:    _CIMGraphService_GetEquipment_Handler,
		},
		{
			MethodName: "ExecuteSPARQL",
			Handler:    _CIMGraphService_ExecuteSPARQL_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CIMGraphService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cimgraph.proto",
}
