// Package web embeds the admin UI's built static SPA assets
// (internal/server/web/dist/, produced by `make ui-build` from the Svelte
// source under internal/server/web/frontend/) into the server binary.
// Node and npm are build-time-only dependencies: the compiled Go binary
// carries only the static assets below.
//
// The "all:" prefix on the embed directive includes files whose name
// begins with "." or "_" (Go's default embed pattern excludes them). The
// built Vite output here does not currently produce such files, but
// "all:" is the correct default for a directory generated by an external
// build step this package does not control.
package web

import "embed"

//go:embed all:dist
var DistFS embed.FS
